export const NAVIGATION_OPEN = 'NAVIGATION_OPEN';
export const NAVIGATION_CLOSE = 'NAVIGATION_CLOSE';
export const NAVIGATION_TOGGLE = 'NAVIGATION_TOGGLE';
export const NAVIGATION_SET_PAGE = 'NAVIGATION_SET_PAGE';
